[build]
  command = "pnpm exec turbo run build --filter=web"

[build.environment]
  NODE_VERSION = "24"

[[plugins]]
  package = "/netlify/plugins/neon-db"

[[plugins]]
  package = "netlify-plugin-inngest"

  [plugins.inputs]
    path = "/api/inngest"
